### ISSUE TITLE
언어 도메인 조회 기능 개발, 비건 단계 출력 로직 수정

### ISSUE THREAD

**Issue by wolveshowl** [Chae-So/Back-End#18]
## Description
언어 도메인 조회 기능 개발, 비건 단계 출력 로직 수정

## Todo
- [x] 언어 도메인 조회 기능 개발
- [x] 비건 단계 출력 로직 수정
- [x] 커뮤니티 도메인 테스트 코드 수정
