### ISSUE TITLE
Report 도메인 API 기능 구현

### ISSUE THREAD

**Issue by wolveshowl** [Chae-So/Back-End#29]
## Description
악의적인 게시글과 댓글을 신고 할 수 있도록 기능을 구현했습니다.

## Todo
- [x] PostType이라는 변수로 게시글인지 댓글인지("C", "R") 판단하고 알맞게 신고 데이터가 쌓일 수 있도록
- [x] 게시글 또는 댓글의 일련번호와 신고 당한 회원의 일련번호도 나타낼 수 있도록 함.
- [x] 회원의 일련번호를 나타낸 이유는 해당 회원의 게시물에 신고 횟수가 많을때 후속 조치를 취할 수 있도록 명시적으로 컬럼에 추가
